defaults:
  - scope:
      path: abba/html
    values:
      layout: compress
      have_breadcrumb: true
      have_filter: true
  - scope:
      path: previews
    values:
      asset_dir: ../../abba
      server_date: "2020-09-14T09:23:00"

compress_html:
    clippings: all
