defaults:
  - scope:
      path: abba/html
    values:
      layout: compress
  - scope:
      path: previews
    values:
      layout: preview
      asset_dir: ../../abba

compress_html:
    clippings: all
