defaults:
  - scope:
      path: abba/html
    values:
      layout: compress
      asset_dir: /.abba
      css_filename: style.css
      have_breadcrumb: true
      have_filter: true
      title: "<!--#echo var=SERVER_NAME -->"
      server_date: "<!--#config timefmt=%FT%T --><!--#echo var=DATE_LOCAL -->"
  - scope:
      path: previews
    values:
      asset_dir: ../../abba
      server_date: "2020-09-14T09:23:00"

compress_html:
    clippings: all
