sass:
    sass_dir: _scss
    style: compressed
defaults:
    -
        scope:
            path: ""
        values:
            layout: default
            assets: /dist
            css: default
            js: script
            title: abba.jmldev.net
gems:
    - jekyll-sitemap
