name: "Publish Docker image"

on: push

jobs:
  push_to_registry:
    name: "Push Docker image to Docker Hub"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4.1.1

      - name: "Log in to Docker Hub"
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Extract metadata (tags, labels) for Docker"
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: jmlemetayer/abba
          flavor: |
            latest=true

      - name: "Build and push Docker image"
        uses: docker/build-push-action@v5.3.0
        with:
          context: docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
