name: "Update dependencies"

on:
  schedule:
    - cron:  "31 5 * * *"
  workflow_dispatch:

jobs:
  update_dependencies:
    name: "Update dependencies"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3.5.2

      - name: "Setup python"
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.8

      - name: "Install Python dependencies"
        uses: py-actions/py-dependency-install@v4.0.0
        with:
          path: "tools/dependencies/requirements.txt"

      - name: "Update dependencies"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ./tools/dependencies/update_dependencies

      - name: "Create Pull Request"
        uses: peter-evans/create-pull-request@v5.0.1
        with:
          title: "Update dependencies"
          body: "ABBA dependency updates"
          delete-branch: true

